### ISSUE TITLE
Ability to run specific flows

### ISSUE THREAD

**Issue by orelviz** [mobile-dev-inc/action-maestro-cloud#11]
Can we add the ability to run only specific flows from a list?
Sometimes you don't want to run by tags, you only want to validate the `settings` section of the app for example.
It would be useful to be able to define a specific list of flows to run

**Comment by dmitry-zaitsev** [comment]
Tags were created exactly with that use-case in mind. In your example, I would add `settings` tag to settings-related flows and run it that way.

Is there any particular reason that tags are not convenient for you?

**Comment by dmitry-zaitsev** [comment]
cc @ArthurSav

**Comment by orelviz** [comment]
Thank you @dmitry-zaitsev !
I thoughts of tags as a different feature, like if I want to collect flows as `sanity` or `regressions` etc.
But sometimes you want to run tests on just one screen, or just one or two flows. Are you suggesting adding a tag to each flow with the name of that flow?

**Comment by axelniklasson** [comment]
@orelviz you can use different inclusion patterns in `config.yaml` to define what Flows to run if you do not want to use tags. More info on this [here](https://maestro.mobile.dev/cli/test-suites-and-reports#inclusion-patterns) -- let me know if that doesn't work for you!
