### ISSUE TITLE
Support for appBinaryId in GitHub Actions for E2E Testing with Expo

### ISSUE THREAD

**Issue by pfolegmalkov** [mobile-dev-inc/action-maestro-cloud#22]
👋 Hey team,

Summary:
Currently, this GitHub Action for E2E testing requires a path to the binary. Since we're using Expo and generating binaries less frequently (1-2 weeks), it would be more efficient to trigger tests using appBinaryId.

Details:
Current Behavior: The action requires a binary path.
Desired Behavior: Use appBinaryId to locate the app for E2E tests.
Benefit: This would allow us to manually trigger E2E tests without needing uploading the binary every time.

**Comment by axelniklasson** [comment]
Thanks for raising this feature request @pfolegmalkov. This is something we want to add, so stay tuned for this! cc @ArthurSav

**Comment by axelniklasson** [comment]
This was landed [here](https://github.com/mobile-dev-inc/action-maestro-cloud/commit/1e1571a448e85b46b2398a98ddef062532c0ac0a) and went out in 1.6.0, so closing this out. Hope you like it @pfolegmalkov :)
