### ISSUE TITLE
Back and forth between the Running and Pending states creates unexpected data and causes failure

### ISSUE THREAD

**Issue by omid-ebrahimi** [mobile-dev-inc/action-maestro-cloud#37]
Maestro Cloud is running one of my flows until a certain state then it comes back to a pending state and then run it again. Because of this behavior, it has changed some data in the test environment in the first run, and the next time it goes to the running state it fails as expected.

I see we have a [retry mechanism](https://cloud.mobile.dev/reference/retries) in the Maestro Cloud that re-runs the test in case of failure, but if we can't see the video (and logs) for the first failed flow we can't find the issue easily. Also, I think we should be able to **disable this retry feature** if we need to.

**Comment by mskhan18** [comment]
Any update @omid-ebrahimi

**Comment by omid-ebrahimi** [comment]
> Any update @omid-ebrahimi

@mskhan18 In the latest version of Maestro you can add a `disableRetries: true` to your `config.yaml` file. It will disable retries that are happening because of failed test cases, but it will still do the retry when something goes wrong with the Maestro Cloud itself.
