### ISSUE TITLE
Maestro cloud + Github Action failed with error

### ISSUE THREAD

**Issue by hivenet-sathishgadde-osi** [mobile-dev-inc/action-maestro-cloud#41]
Error: Could not get Upload status - received error Error: Request to https://api.mobile.dev/v2/upload/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/status?includeErrors=true failed (500): java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30058ms.. View the Upload in the console for more information: https://console.mobile.dev/uploads/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?teamId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&appId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

**Comment by Fishbowler** [comment]
This was the result of a historic incident, and can now be closed.
